/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IBaseEscrow {
  export type ImmutablesStruct = {
    orderHash: BytesLike;
    hashlock: BytesLike;
    maker: BigNumberish;
    taker: BigNumberish;
    token: BigNumberish;
    amount: BigNumberish;
    safetyDeposit: BigNumberish;
    timelocks: BigNumberish;
  };

  export type ImmutablesStructOutput = [
    orderHash: string,
    hashlock: string,
    maker: bigint,
    taker: bigint,
    token: bigint,
    amount: bigint,
    safetyDeposit: bigint,
    timelocks: bigint
  ] & {
    orderHash: string;
    hashlock: string;
    maker: bigint;
    taker: bigint;
    token: bigint;
    amount: bigint;
    safetyDeposit: bigint;
    timelocks: bigint;
  };
}

export declare namespace IOrderMixin {
  export type OrderStruct = {
    salt: BigNumberish;
    maker: BigNumberish;
    receiver: BigNumberish;
    makerAsset: BigNumberish;
    takerAsset: BigNumberish;
    makingAmount: BigNumberish;
    takingAmount: BigNumberish;
    makerTraits: BigNumberish;
  };

  export type OrderStructOutput = [
    salt: bigint,
    maker: bigint,
    receiver: bigint,
    makerAsset: bigint,
    takerAsset: bigint,
    makingAmount: bigint,
    takingAmount: bigint,
    makerTraits: bigint
  ] & {
    salt: bigint;
    maker: bigint;
    receiver: bigint;
    makerAsset: bigint;
    takerAsset: bigint;
    makingAmount: bigint;
    takingAmount: bigint;
    makerTraits: bigint;
  };
}

export declare namespace IEscrowFactory {
  export type DstImmutablesComplementStruct = {
    maker: BigNumberish;
    amount: BigNumberish;
    token: BigNumberish;
    safetyDeposit: BigNumberish;
    chainId: BigNumberish;
  };

  export type DstImmutablesComplementStructOutput = [
    maker: bigint,
    amount: bigint,
    token: bigint,
    safetyDeposit: bigint,
    chainId: bigint
  ] & {
    maker: bigint;
    amount: bigint;
    token: bigint;
    safetyDeposit: bigint;
    chainId: bigint;
  };
}

export interface TestEscrowFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ESCROW_DST_IMPLEMENTATION"
      | "ESCROW_SRC_IMPLEMENTATION"
      | "FEE_BANK"
      | "addressOfEscrowDst"
      | "addressOfEscrowSrc"
      | "availableCredit"
      | "createDstEscrow"
      | "decreaseAvailableCredit"
      | "getMakingAmount"
      | "getTakingAmount"
      | "increaseAvailableCredit"
      | "lastValidated"
      | "postInteraction"
      | "preInteraction"
      | "takerInteraction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DstEscrowCreated" | "SrcEscrowCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ESCROW_DST_IMPLEMENTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ESCROW_SRC_IMPLEMENTATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FEE_BANK", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addressOfEscrowDst",
    values: [IBaseEscrow.ImmutablesStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addressOfEscrowSrc",
    values: [IBaseEscrow.ImmutablesStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "availableCredit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDstEscrow",
    values: [IBaseEscrow.ImmutablesStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decreaseAvailableCredit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMakingAmount",
    values: [
      IOrderMixin.OrderStruct,
      BytesLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getTakingAmount",
    values: [
      IOrderMixin.OrderStruct,
      BytesLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseAvailableCredit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lastValidated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "postInteraction",
    values: [
      IOrderMixin.OrderStruct,
      BytesLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "preInteraction",
    values: [
      IOrderMixin.OrderStruct,
      BytesLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "takerInteraction",
    values: [
      IOrderMixin.OrderStruct,
      BytesLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "ESCROW_DST_IMPLEMENTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ESCROW_SRC_IMPLEMENTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE_BANK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addressOfEscrowDst",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addressOfEscrowSrc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDstEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decreaseAvailableCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMakingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTakingAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseAvailableCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastValidated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "postInteraction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "preInteraction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "takerInteraction",
    data: BytesLike
  ): Result;
}

export namespace DstEscrowCreatedEvent {
  export type InputTuple = [
    escrow: AddressLike,
    hashlock: BytesLike,
    taker: BigNumberish
  ];
  export type OutputTuple = [escrow: string, hashlock: string, taker: bigint];
  export interface OutputObject {
    escrow: string;
    hashlock: string;
    taker: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SrcEscrowCreatedEvent {
  export type InputTuple = [
    srcImmutables: IBaseEscrow.ImmutablesStruct,
    dstImmutablesComplement: IEscrowFactory.DstImmutablesComplementStruct
  ];
  export type OutputTuple = [
    srcImmutables: IBaseEscrow.ImmutablesStructOutput,
    dstImmutablesComplement: IEscrowFactory.DstImmutablesComplementStructOutput
  ];
  export interface OutputObject {
    srcImmutables: IBaseEscrow.ImmutablesStructOutput;
    dstImmutablesComplement: IEscrowFactory.DstImmutablesComplementStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TestEscrowFactory extends BaseContract {
  connect(runner?: ContractRunner | null): TestEscrowFactory;
  waitForDeployment(): Promise<this>;

  interface: TestEscrowFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ESCROW_DST_IMPLEMENTATION: TypedContractMethod<[], [string], "view">;

  ESCROW_SRC_IMPLEMENTATION: TypedContractMethod<[], [string], "view">;

  FEE_BANK: TypedContractMethod<[], [string], "view">;

  addressOfEscrowDst: TypedContractMethod<
    [immutables: IBaseEscrow.ImmutablesStruct],
    [string],
    "view"
  >;

  addressOfEscrowSrc: TypedContractMethod<
    [immutables: IBaseEscrow.ImmutablesStruct],
    [string],
    "view"
  >;

  availableCredit: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  createDstEscrow: TypedContractMethod<
    [
      dstImmutables: IBaseEscrow.ImmutablesStruct,
      srcCancellationTimestamp: BigNumberish
    ],
    [void],
    "payable"
  >;

  decreaseAvailableCredit: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getMakingAmount: TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      arg1: BytesLike,
      arg2: BytesLike,
      arg3: AddressLike,
      takingAmount: BigNumberish,
      arg5: BigNumberish,
      extraData: BytesLike
    ],
    [bigint],
    "view"
  >;

  getTakingAmount: TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      arg1: BytesLike,
      arg2: BytesLike,
      arg3: AddressLike,
      makingAmount: BigNumberish,
      arg5: BigNumberish,
      extraData: BytesLike
    ],
    [bigint],
    "view"
  >;

  increaseAvailableCredit: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  lastValidated: TypedContractMethod<
    [key: BytesLike],
    [[bigint, string] & { index: bigint; leaf: string }],
    "view"
  >;

  postInteraction: TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      extension: BytesLike,
      orderHash: BytesLike,
      taker: AddressLike,
      makingAmount: BigNumberish,
      takingAmount: BigNumberish,
      remainingMakingAmount: BigNumberish,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  preInteraction: TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      extension: BytesLike,
      orderHash: BytesLike,
      taker: AddressLike,
      makingAmount: BigNumberish,
      takingAmount: BigNumberish,
      remainingMakingAmount: BigNumberish,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  takerInteraction: TypedContractMethod<
    [
      arg0: IOrderMixin.OrderStruct,
      extension: BytesLike,
      orderHash: BytesLike,
      arg3: AddressLike,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ESCROW_DST_IMPLEMENTATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ESCROW_SRC_IMPLEMENTATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FEE_BANK"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addressOfEscrowDst"
  ): TypedContractMethod<
    [immutables: IBaseEscrow.ImmutablesStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "addressOfEscrowSrc"
  ): TypedContractMethod<
    [immutables: IBaseEscrow.ImmutablesStruct],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "availableCredit"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "createDstEscrow"
  ): TypedContractMethod<
    [
      dstImmutables: IBaseEscrow.ImmutablesStruct,
      srcCancellationTimestamp: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "decreaseAvailableCredit"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMakingAmount"
  ): TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      arg1: BytesLike,
      arg2: BytesLike,
      arg3: AddressLike,
      takingAmount: BigNumberish,
      arg5: BigNumberish,
      extraData: BytesLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTakingAmount"
  ): TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      arg1: BytesLike,
      arg2: BytesLike,
      arg3: AddressLike,
      makingAmount: BigNumberish,
      arg5: BigNumberish,
      extraData: BytesLike
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "increaseAvailableCredit"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lastValidated"
  ): TypedContractMethod<
    [key: BytesLike],
    [[bigint, string] & { index: bigint; leaf: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "postInteraction"
  ): TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      extension: BytesLike,
      orderHash: BytesLike,
      taker: AddressLike,
      makingAmount: BigNumberish,
      takingAmount: BigNumberish,
      remainingMakingAmount: BigNumberish,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "preInteraction"
  ): TypedContractMethod<
    [
      order: IOrderMixin.OrderStruct,
      extension: BytesLike,
      orderHash: BytesLike,
      taker: AddressLike,
      makingAmount: BigNumberish,
      takingAmount: BigNumberish,
      remainingMakingAmount: BigNumberish,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "takerInteraction"
  ): TypedContractMethod<
    [
      arg0: IOrderMixin.OrderStruct,
      extension: BytesLike,
      orderHash: BytesLike,
      arg3: AddressLike,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BigNumberish,
      extraData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DstEscrowCreated"
  ): TypedContractEvent<
    DstEscrowCreatedEvent.InputTuple,
    DstEscrowCreatedEvent.OutputTuple,
    DstEscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SrcEscrowCreated"
  ): TypedContractEvent<
    SrcEscrowCreatedEvent.InputTuple,
    SrcEscrowCreatedEvent.OutputTuple,
    SrcEscrowCreatedEvent.OutputObject
  >;

  filters: {
    "DstEscrowCreated(address,bytes32,uint256)": TypedContractEvent<
      DstEscrowCreatedEvent.InputTuple,
      DstEscrowCreatedEvent.OutputTuple,
      DstEscrowCreatedEvent.OutputObject
    >;
    DstEscrowCreated: TypedContractEvent<
      DstEscrowCreatedEvent.InputTuple,
      DstEscrowCreatedEvent.OutputTuple,
      DstEscrowCreatedEvent.OutputObject
    >;

    "SrcEscrowCreated(tuple,tuple)": TypedContractEvent<
      SrcEscrowCreatedEvent.InputTuple,
      SrcEscrowCreatedEvent.OutputTuple,
      SrcEscrowCreatedEvent.OutputObject
    >;
    SrcEscrowCreated: TypedContractEvent<
      SrcEscrowCreatedEvent.InputTuple,
      SrcEscrowCreatedEvent.OutputTuple,
      SrcEscrowCreatedEvent.OutputObject
    >;
  };
}
